// <auto-generated />
namespace StadiumTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatedvisitproperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedvisitproperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201808152318523_updatedvisitproperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
